apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-kube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-kube
  template:
    metadata:
      labels:
        app: node-kube
    spec:
      containers:
        - name: app
          image: eslamsalem/node-kube:1.0.0
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URL
              value: mongodb://mongo:27017/dev
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: node-kube
spec:
  selector:
    app: node-kube
  ports:
    - port: 80
      targetPort: 3000
  type: LoadBalancer